dist: trusty
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.4
gemfile:
  - Gemfile

before_install:
  - TAG=$(git describe --tags)
  - echo "export rvm_ignore_gemsets_flag=1" >> ~/.rvmrc
  - gem install bundler -v 1.15.1

install:
  - bundle install --jobs=4 --retry=3 --path vendor/bundle
  - echo $TAG | tr -d v,V > VERSION

script:
  - bundle exec rspec spec

deploy:
  provider: script
  on:
    tags: true
  skip_cleanup: true # prevent removing vendored gems needed by deploy scropt
  script: rvm $TRAVIS_RUBY_VERSION --verbose do ./deploy.sh # dpl runs script in another ruby env, need to switch back with rvm

env:
  global:
    - TZ='US/Eastern'
    # GEM_PASSWORD
    - secure: "v8pW5UZewoA3E1hAE94Z1uDIeCF1qgNHobaxoy4wCqLN/E5ZCI8u6ce6jiFgtOuCjhPLRZU0/6rzoViF7jeSLGNA5AmYuFwZ1+uDebQNRRVS7EP1EON0uKad27Kf4P4tcxESfFxWKK8+DziAsvrdHA+q7FUxI9EpXcuDXK70ExKFFCM3LhFunhU48dxgxkDXBkKJAA98Su1QQlYCFiPVfwpYevtRDTO9LR/7MZ1E4jSSM3aA//zLraqXKaQr0FhYP1Zq4O1qN0WN7zHarBmw31+GRf0rb+O14w/cNxi85XKTZjiCScku3lnT21k5lWSPyPaUMEfNTn0/u8jreNn2Nq/8Gq5hlr5bM0M0Va50Kd8h6nw8tP7ZsaTCa22CGgXCa6rV9RDpUSJmPw3D1kuBtsdfGlFpgjeKi9ab+zHu85HQq+CXcFch3GTtuGeXruHxRGcWOYWBOPzLIgbXHJ0aIpxk3qF+A7Xy9gCMMBY6/RpKsweWnjfbluPWu2wUrPaHUz+31sbzgw7PJGbeEKO/WiZGABKLG4qg5ZytZK+CKfFV4ut4oFqoGHdLKabpy57dZyLHTf8wf+DXoK2xw+nZHSZalHIVIOsqvZ8lvd9EWzQ/NoJQg1JMFpF5c0xz3kgf9pyU6Y2MgtQsI+VKkjQ0ucqPNrPPfIwtjG0+0fnXlaQ="

notifications:
  slack:
    secure: PyjyVA4cTEM2GMgodFl1KjEt/6FDqGSq82HmYk254mm0x65pIiE688XnPiNJGygk+w544PwQ0c9Z19ijkAKUustuXAfc5f9/rtedUAtjq12m61rVF+TeLMjVBc2A7mHcb/Yg2y/kgO6PESQLsrTSIAqXrO/srgfPGvuvLAsh0yy3KG7ZFX3sJu1kqzk0osE11MHhDZQGH5ABjuMp6DLLJtPbLe7Ei0n6T46peEcxVcQu4BMFTKvcCjbUQQmKNz3pTFlYEceZMhhO6+GbXbT47hD+6rFAMs91bT7v+kdg8ARsH+PSdHiPzp8Kuh3wuivgnJscjIalghCD5WgwKwvrEDRvAi75d2wNPaeN6D//tVRdkx3DBXOS1oDdsc4W3vtO3FNnuEAvMXj2KAkfgEJIhblR7cJB0+cWbcIKVVIB/k4Fa14Xx06fgxLnf/oYt/utRj7sVmvDlvqttDqcLryFQwHMQ6mYeFr8lLoBSGp7IP4d+4dRSXVrKmSvE1ZXJAFpo+Qb/oBqAxJT0JJ+tCBUL/h8VQFni9UyLHhJJhnjuoTy4vrtEALp263L8TnRhUJhvfDxbuNhKSh6n5nuSowkp8gTklP6pJGMQafvcbEqTdHqQMLOJpRhrzCKhVP0QCo4FW4lu39mIkeYO+hPkCOCVF/KcugPwvvbfR82D8tZWzw=
