dist: trusty
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.4
gemfile:
  - Gemfile

before_install:
  - TAG=$(git describe --tags)
  - echo "export rvm_ignore_gemsets_flag=1" >> ~/.rvmrc
  - gem install bundler -v 1.15.1

install:
  - bundle install --jobs=4 --retry=3 --path vendor/bundle
  - echo $TAG | tr -d v,V > VERSION

script:
  - bundle exec rspec spec

deploy:
  provider: script
  on:
    tags: true
  skip_cleanup: true # prevent removing vendored gems needed by deploy scropt
  script: rvm $TRAVIS_RUBY_VERSION --verbose do ./deploy.sh # dpl runs script in another ruby env, need to switch back with rvm

env:
  global:
  - TZ='US/Eastern'
  - secure: VgFrc6mFg7a/C9FERjTq8dfnKNaWA48lSkxlKdaJMAmUjHrzC5j/TNd1PNORPilFpPRuIslX17RdNiKO280kDuKsl7L32PL9iNhqbXQVGhzyppkAIsllVJW2RPa/9BS6MYzKG4i1QlNy3hu2TViXAiv25oNQhqmzALomfbKcsFudL4D+yw9CZJt8IDYPYluGhFdz0L41D7Om1OtwxzpngBg6e1rdLQVjxuzjxlR2XSyLv3OuTujrMAaU7tojaiIF7jFpDGoXbBYsvZhrw+8k/6GWkYT7JzyfMG+Cs3J6tGhbR55IWV/doW4BaTtIPmqDfGZV08hkAA3Zj4rPxEXi+/K/QfZICg1hQpObOoWhYqzAXEjrDujcCf4CjxatVHvPA/iIx622TCbrA6gZuahm4RT0KJI1aTon9Pd5jjHbp6S/AYFqpDa/WCPZvgLADPfRVyijlJl/DyuE3+ULC8RldGk3kRMredxKMfcjqGrLyMSFQTNOqWeIcFbHroTvA8DRqvHm+vOqDfyDPChH8vKJCmgGF9GOfQAKNSvE8Qbr6KbNlQKbWk0vdG7ARyG/O0yaNHTUN/qt4CW/GaWwHuOD43uWVd0YRZ4LqFTNS48P9OdsZqi0h6XF5kSenJ93igAajmhf+zyn0zZWQE+jQqraVEPmw7j1MbIht6CvR0/KyOY=
notifications:
  slack:
    secure: PyjyVA4cTEM2GMgodFl1KjEt/6FDqGSq82HmYk254mm0x65pIiE688XnPiNJGygk+w544PwQ0c9Z19ijkAKUustuXAfc5f9/rtedUAtjq12m61rVF+TeLMjVBc2A7mHcb/Yg2y/kgO6PESQLsrTSIAqXrO/srgfPGvuvLAsh0yy3KG7ZFX3sJu1kqzk0osE11MHhDZQGH5ABjuMp6DLLJtPbLe7Ei0n6T46peEcxVcQu4BMFTKvcCjbUQQmKNz3pTFlYEceZMhhO6+GbXbT47hD+6rFAMs91bT7v+kdg8ARsH+PSdHiPzp8Kuh3wuivgnJscjIalghCD5WgwKwvrEDRvAi75d2wNPaeN6D//tVRdkx3DBXOS1oDdsc4W3vtO3FNnuEAvMXj2KAkfgEJIhblR7cJB0+cWbcIKVVIB/k4Fa14Xx06fgxLnf/oYt/utRj7sVmvDlvqttDqcLryFQwHMQ6mYeFr8lLoBSGp7IP4d+4dRSXVrKmSvE1ZXJAFpo+Qb/oBqAxJT0JJ+tCBUL/h8VQFni9UyLHhJJhnjuoTy4vrtEALp263L8TnRhUJhvfDxbuNhKSh6n5nuSowkp8gTklP6pJGMQafvcbEqTdHqQMLOJpRhrzCKhVP0QCo4FW4lu39mIkeYO+hPkCOCVF/KcugPwvvbfR82D8tZWzw=
